### ISSUE TITLE
SteamOS doesn't boot after 3.5 update

### ISSUE THREAD

**Issue by miqosu** [jlobue10/SteamDeck_rEFInd#70]
I set up rEFInd yesterday with steamos and windows 11. Everything worked perfectly. Today I decided to update SteamOS to 3.5. Some things happend and as of now I'm able to launch SteamOS using Volume + and Power and everything works Windows aswell.
When I turn on steamdeck I get the rEFInd menu but when I choose SteamOS icon it doesn't work. Windows works just fine tho and my NTFS sd card too. Is there a way to fix this?

**Comment by jlobue10** [comment]
Can you manually boot into SteamOS and show me the output of `efibootmgr` and what your `refind.conf` file looks like?

**Comment by miqosu** [comment]
Sure I have to type efibootmgr into Konsole?

**Comment by jlobue10** [comment]
Yes. I need to see that `efibootmgr` output and compare it to your `refind.conf` file. You can see the contents of the in use refind config file with `sudo nano /esp/efi/refind/refind.conf`.

**Comment by jlobue10** [comment]
I see the problem. Change the line in the SteamOS stanza from `firmware_bootnum 0001` to `firmware_bootnum 0000`.

Then press `ctrl+x` followed by 'y' to exit `nano` with changes saved. Reboot and all should be fixed.

**Comment by miqosu** [comment]
I think I do something wrong when I do this and press Y I'm stil in konsole and when i exit it and type this again it still shows firmware_bootnum 0001

**Comment by jlobue10** [comment]
You may need to run this first before editing `sudo steamos-readonly disable`.

Or you can manually edit or recreate the `refind.conf` file in the `/home/deck/.SteamDeck_rEFInd/GUI/` folder (hidden folder, by the way) and perform the Install Config step from the GUI.

**Comment by miqosu** [comment]
It works! But right now when I shut down SteamOS it shutdowns and goes to black screen (screen still have light on) and I have to long press Power button for screen to shut down. Do you know why it happends or it's just minor inconvinience

**Comment by miqosu** [comment]
I just checked and it doesn't happen on Windows

**Comment by jlobue10** [comment]
I'm not sure about that. Maybe some issue with 3.5 since that's not released as stable yet. If you're happy with the resolution, then please close the issue. Thanks.

**Comment by miqosu** [comment]
Right that might be it. Thank you very much!
